PREFIX ?= /usr/local
BINARY = bgbgone
VERSION_FILE = .version

.PHONY: check-toolchain build install uninstall clean bump-patch bump-minor bump-major generate-build-info update-readme version test test-unit test-integration performance-100 test-performance-100 perf-100 fixtures package-release-asset print-release-asset print-release-sha256 readme-images release

# --- Environment ---

check-toolchain:
	@sdk=$$(xcrun --show-sdk-version 2>/dev/null || echo "missing"); \
	if [ "$$sdk" = "missing" ]; then \
		echo "error: bgbgone could not determine your active Apple SDK version."; \
		echo "Install or update Command Line Tools, then retry: xcode-select --install"; \
		exit 1; \
	fi

# --- Build (auto-bumps patch) ---

build: check-toolchain
	$(MAKE) bump-patch
	$(MAKE) generate-build-info
	$(MAKE) update-readme
	swift build -c release

install: build
	@if [ -w "$(PREFIX)/bin" ]; then \
		install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	else \
		sudo install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	fi
	@echo "installed: $$($(PREFIX)/bin/$(BINARY) --version)"

# --- Tests ---

test: test-unit test-integration

test-unit: check-toolchain generate-build-info
	swift run bgbgone-tests

test-integration: build
	bash Tests/integration/run.sh .build/release/$(BINARY)

performance-100:
	bash Tests/performance/run-100.sh .build/release/$(BINARY)

test-performance-100 perf-100: build performance-100

fixtures:
	bash scripts/fetch-fixtures.sh

# --- Version bumps ---

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

# --- Generated files ---

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null | head -1); \
	if [ -z "$$commit" ]; then commit="unknown"; fi; \
	branch=$$(git symbolic-ref --short -q HEAD 2>/dev/null | head -1); \
	if [ -z "$$branch" ]; then branch="unknown"; fi; \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make — do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

update-readme:
	@v=$$(cat $(VERSION_FILE)); \
	sed -i '' 's/Version [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/Version '"$$v"'/' README.md 2>/dev/null || true; \
	sed -i '' 's/version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue/version-'"$$v"'-blue/' README.md 2>/dev/null || true

# --- Utilities ---

version:
	@cat $(VERSION_FILE)

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		rm -f $(PREFIX)/bin/$(BINARY); \
	else \
		sudo rm -f $(PREFIX)/bin/$(BINARY); \
	fi

clean:
	swift package clean
	rm -rf Tests/integration/_out Tests/integration/_tmp

package-release-asset:
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	if [ ! -x ".build/release/$(BINARY)" ]; then \
		echo "error: missing .build/release/$(BINARY). Build a release binary first."; \
		exit 1; \
	fi; \
	tar -C .build/release -czf "$$asset" $(BINARY); \
	echo "$$asset"

print-release-asset:
	@v=$$(cat $(VERSION_FILE)); \
	echo "bgbgone-$$v-arm64-macos.tar.gz"

print-release-sha256:
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	if [ ! -f "$$asset" ]; then \
		echo "error: missing $$asset. Run make package-release-asset first."; \
		exit 1; \
	fi; \
	shasum -a 256 "$$asset" | awk '{print $$1}'

# Regenerate every showcase image in docs/images/ from the installed binary.
# Release MUST run this so the README always matches the shipped behaviour —
# regressions like the v0.1.16 feather/colour-space bug ship visibly otherwise.
readme-images: install
	bash scripts/make-readme-examples.sh

# Full release gate: bump → test → install → regenerate README images →
# package. Use this for every public release; never tag without it.
release: test install readme-images performance-100 package-release-asset
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	echo ""; \
	echo "release ready:"; \
	echo "  version : $$v"; \
	echo "  binary  : $(PREFIX)/bin/$(BINARY) ($$($(PREFIX)/bin/$(BINARY) --version))"; \
	echo "  tarball : $$asset ($$(shasum -a 256 $$asset | awk '{print $$1}'))"
