PREFIX ?= /usr/local
BINARY = bgbgone
VERSION_FILE = .version

.PHONY: check-toolchain build install uninstall clean bump-patch bump-minor bump-major generate-build-info update-readme version test test-unit test-integration lint lint-fixtures lint-readme lint-docs lint-contract performance-100 test-performance-100 perf-100 performance-1000 test-performance-1000 perf-1000 performance-10000 test-performance-10000 perf-10000 perf-10k fixtures package-release-asset print-release-asset print-release-sha256 readme-images filter-images panel-images filter-docs all-images release deploy

# --- Environment ---

check-toolchain:
	@sdk=$$(xcrun --show-sdk-version 2>/dev/null || echo "missing"); \
	if [ "$$sdk" = "missing" ]; then \
		echo "error: bgbgone could not determine your active Apple SDK version."; \
		echo "Install or update Command Line Tools, then retry: xcode-select --install"; \
		exit 1; \
	fi

# --- Build (auto-bumps patch) ---

build: check-toolchain
	$(MAKE) bump-patch
	$(MAKE) generate-build-info
	$(MAKE) update-readme
	swift build -c release

install: build
	@if [ -w "$(PREFIX)/bin" ]; then \
		install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	else \
		sudo install .build/release/$(BINARY) $(PREFIX)/bin/$(BINARY); \
	fi
	@echo "installed: $$($(PREFIX)/bin/$(BINARY) --version)"

# --- Tests ---

test: lint-fixtures lint-readme lint-contract test-unit test-integration

test-unit: check-toolchain generate-build-info
	swift run bgbgone-tests

test-integration: build
	bash Tests/integration/run.sh .build/release/$(BINARY)

lint-fixtures:
	bash scripts/lint-fixtures.sh

lint-readme:
	bash scripts/lint-readme.sh

lint-contract:
	bash scripts/lint-contract.sh

lint-docs: check-toolchain generate-build-info
	swift build -c release
	bash scripts/lint-docs.sh

lint: lint-fixtures lint-readme lint-contract lint-docs

performance-100:
	bash Tests/performance/run-100.sh .build/release/$(BINARY)

test-performance-100 perf-100: build performance-100

# Optional sustained-throughput stress tests. NOT part of `release` —
# opt-in only. Both call the same parameterised script with different
# invocation counts (batch stays 100). Each re-writes its own README
# result line on every run so the numbers stay current.
performance-1000:
	bash Tests/performance/run-sustained.sh .build/release/$(BINARY) 10

test-performance-1000 perf-1000: build performance-1000

# 100 x 100 = 10,000 image operations.
performance-10000:
	bash Tests/performance/run-sustained.sh .build/release/$(BINARY) 100

test-performance-10000 perf-10000 perf-10k: build performance-10000

fixtures:
	bash scripts/fetch-fixtures.sh

# --- Version bumps ---

bump-patch:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	patch=$$(echo $$v | cut -d. -f3); \
	new="$$major.$$minor.$$((patch+1))"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-minor:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	minor=$$(echo $$v | cut -d. -f2); \
	new="$$major.$$((minor+1)).0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

bump-major:
	@v=$$(cat $(VERSION_FILE)); \
	major=$$(echo $$v | cut -d. -f1); \
	new="$$((major+1)).0.0"; \
	echo "$$new" > $(VERSION_FILE); \
	echo "$$v -> $$new"

# --- Generated files ---

generate-build-info:
	@v=$$(cat $(VERSION_FILE)); \
	commit=$$(git rev-parse --short HEAD 2>/dev/null | head -1); \
	if [ -z "$$commit" ]; then commit="unknown"; fi; \
	branch=$$(git symbolic-ref --short -q HEAD 2>/dev/null | head -1); \
	if [ -z "$$branch" ]; then branch="unknown"; fi; \
	date=$$(date -u +"%Y-%m-%d %H:%M:%S UTC"); \
	swift_ver=$$(swift --version 2>/dev/null | head -1 | sed 's/.*version //' | sed 's/ .*//'); \
	os_ver=$$(sw_vers -productVersion 2>/dev/null || echo "unknown"); \
	echo "// Auto-generated by make — do not edit" > Sources/BuildInfo.swift; \
	echo "let buildVersion = \"$$v\"" >> Sources/BuildInfo.swift; \
	echo "let buildCommit = \"$$commit\"" >> Sources/BuildInfo.swift; \
	echo "let buildBranch = \"$$branch\"" >> Sources/BuildInfo.swift; \
	echo "let buildDate = \"$$date\"" >> Sources/BuildInfo.swift; \
	echo "let buildSwiftVersion = \"$$swift_ver\"" >> Sources/BuildInfo.swift; \
	echo "let buildOS = \"macOS $$os_ver\"" >> Sources/BuildInfo.swift

update-readme:
	@v=$$(cat $(VERSION_FILE)); \
	sed -i '' 's/Version [0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/Version '"$$v"'/' README.md 2>/dev/null || true; \
	sed -i '' 's/version-[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*-blue/version-'"$$v"'-blue/' README.md 2>/dev/null || true

# --- Utilities ---

version:
	@cat $(VERSION_FILE)

uninstall:
	@if [ -w "$(PREFIX)/bin" ]; then \
		bash -c 'source scripts/trash.sh; trash_path "$(PREFIX)/bin/$(BINARY)"'; \
	else \
		sudo bash -c 'source "$(PWD)/scripts/trash.sh"; trash_path "$(PREFIX)/bin/$(BINARY)"'; \
	fi

clean:
	bash -c 'source scripts/trash.sh; trash_path .build Tests/integration/_out Tests/integration/_tmp'

package-release-asset:
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	if [ ! -x ".build/release/$(BINARY)" ]; then \
		echo "error: missing .build/release/$(BINARY). Build a release binary first."; \
		exit 1; \
	fi; \
	tar -C .build/release -czf "$$asset" $(BINARY); \
	echo "$$asset"

print-release-asset:
	@v=$$(cat $(VERSION_FILE)); \
	echo "bgbgone-$$v-arm64-macos.tar.gz"

print-release-sha256:
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	if [ ! -f "$$asset" ]; then \
		echo "error: missing $$asset. Run make package-release-asset first."; \
		exit 1; \
	fi; \
	shasum -a 256 "$$asset" | awk '{print $$1}'

# Regenerate every showcase image in docs/images/ from the installed binary.
# Release MUST run this so the README always matches the shipped behaviour —
# regressions like the v0.1.16 feather/colour-space bug ship visibly otherwise.
readme-images: install
	bash scripts/make-readme-examples.sh

# Regenerate the 49 single-filter showcase images on the red-panda fixture
# plus the five hero before/after pairs.
filter-images: install
	BIN=$(PREFIX)/bin/$(BINARY) bash scripts/make-filter-showcase.sh

# Regenerate the per-filter yoga + parastoo 4-panel comparisons
# (original | bg | fg | all).
panel-images: install
	BIN=$(PREFIX)/bin/$(BINARY) bash scripts/make-perfilter-panels.sh

# Regenerate the 49 per-filter markdown pages (docs/filters/*.md).
filter-docs:
	bash scripts/gen-filter-docs.sh

# Regenerate EVERY shipped image: filter showcase, per-filter panels,
# per-filter docs, README examples. Required after every change per
# CLAUDE.md "every release regenerates every image".
all-images: filter-images panel-images filter-docs readme-images
	@echo "all-images: 49 per-filter + 96 panels + 49 docs + README composites regenerated"

# Full release gate: bump → test → install → regenerate EVERY image →
# package. Use this for every public release; never tag without it.
release: lint test install all-images performance-100 package-release-asset
	@v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	echo ""; \
	echo "release ready:"; \
	echo "  version : $$v"; \
	echo "  binary  : $(PREFIX)/bin/$(BINARY) ($$($(PREFIX)/bin/$(BINARY) --version))"; \
	echo "  tarball : $$asset ($$(shasum -a 256 $$asset | awk '{print $$1}'))"

# Single end-to-end deploy: release gate -> stage all -> commit -> tag ->
# push -> GitHub release -> homebrew tap bump. The ONE command that
# ships a new version. Aborts if the working tree contains changes that
# don't belong in the deploy commit (commit them first).
#
# Required env: gh authenticated. Optional: DEPLOY_MESSAGE="..." sets the
# commit/tag subject; defaults to "vX.Y.Z - release".
deploy: release
	@set -e; \
	v=$$(cat $(VERSION_FILE)); \
	asset="bgbgone-$$v-arm64-macos.tar.gz"; \
	sha=$$(shasum -a 256 "$$asset" | awk '{print $$1}'); \
	msg="$${DEPLOY_MESSAGE:-v$$v - release}"; \
	echo ""; \
	echo "deploy: v$$v"; \
	echo "  asset : $$asset"; \
	echo "  sha256: $$sha"; \
	echo ""; \
	echo "==> staging changes"; \
	git add -A; \
	if git diff --cached --quiet; then \
		echo "deploy: working tree clean - skipping commit"; \
	else \
		git commit -m "$$msg" -m "Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"; \
	fi; \
	echo "==> tagging v$$v"; \
	if git tag --list "v$$v" | grep -q "v$$v"; then \
		echo "deploy: tag v$$v already exists - skipping tag"; \
	else \
		git tag -a "v$$v" -m "$$msg"; \
	fi; \
	echo "==> pushing main + tag"; \
	git push origin main; \
	git push origin "v$$v" || true; \
	echo "==> creating GitHub release"; \
	if gh release view "v$$v" >/dev/null 2>&1; then \
		echo "deploy: GitHub release v$$v already exists - skipping create"; \
	else \
		gh release create "v$$v" "$$asset" \
			--title "v$$v" \
			--notes "Automated deploy. SHA-256: $$sha"; \
	fi; \
	echo "==> updating homebrew tap"; \
	bash scripts/update-homebrew-tap.sh "$$v" "$$sha" || echo "deploy: homebrew tap update failed - update manually"; \
	echo ""; \
	echo "deploy complete: https://github.com/Arthur-Ficial/bgbgone/releases/tag/v$$v"
