import Foundation

public enum OutputFormat: String, Sendable, Equatable {
    case png
    case jpeg = "jpg"
    case zip
    case heic
    case avif
    case tiff
}

public enum OutputMode: Sendable, Equatable {
    case standard
    case json
    case ndjson
}

public enum Background: Sendable, Equatable {
    case transparent
    case solidColor(RGBA)
    case image(String)            // path
}

public enum Algo: String, Sendable, Equatable {
    case auto
    case vnMask = "vn-mask"
    case person
    case saliency
}

public enum BgFit: String, Sendable, Equatable {
    case cover
    case contain
    case tile
    case center
}

public struct Config: Sendable, Equatable {
    public enum Mode: Sendable, Equatable {
        case helpRequested
        case versionRequested
        case capabilityCheckRequested
        case serverRequested
        case filtersListRequested
        case process
    }

    public var mode: Mode
    public var inputs: [String]
    public var output: String?
    public var outputDir: String?
    public var outputFormat: OutputFormat
    public var quality: Int
    public var background: Background
    public var bgFit: BgFit
    public var algo: Algo
    public var maskOnly: Bool
    public var feather: Double
    public var threshold: Double?
    public var padding: Double?           // px; percentage stored as 0..1
    public var paddingIsPercent: Bool
    public var cropMargins: ServerEdgeInsets?
    public var cropToSubject: Bool
    public var roi: ServerRectSpec?
    public var scalePercent: Double?
    public var position: ServerPosition?
    public var maxOutputMegapixels: Double?
    public var semitransparency: Bool
    public var dropShadow: Bool
    public var shadowOpacity: Double
    public var multiInstance: Bool
    public var instanceNamingTemplate: String
    public var outputMode: OutputMode
    public var autoFileOutput: Bool
    public var quiet: Bool
    public var verbose: Bool
    public var server: ServerConfig
    public var filters: [FilterChain]

    public init(mode: Mode = .helpRequested) {
        self.mode = mode
        self.inputs = []
        self.output = nil
        self.outputDir = nil
        self.outputFormat = .png
        self.quality = 92
        self.background = .transparent
        self.bgFit = .cover
        self.algo = .auto
        self.maskOnly = false
        self.feather = 1.0
        self.threshold = nil
        self.padding = nil
        self.paddingIsPercent = false
        self.cropMargins = nil
        self.cropToSubject = false
        self.roi = nil
        self.scalePercent = nil
        self.position = nil
        self.maxOutputMegapixels = nil
        self.semitransparency = true
        self.dropShadow = false
        self.shadowOpacity = 0.50
        self.multiInstance = false
        self.instanceNamingTemplate = "{base}-{n}.{ext}"
        self.outputMode = .standard
        self.autoFileOutput = false
        self.quiet = false
        self.verbose = false
        self.server = ServerConfig()
        self.filters = []
    }
}

public struct ServerConfig: Sendable, Equatable {
    public var host: String
    public var port: Int
    public var cors: Bool
    public var allowedOrigins: [String]
    public var originCheckEnabled: Bool
    public var token: String?
    public var tokenWasAutoGenerated: Bool
    public var publicHealth: Bool
    public var maxBodyBytes: Int

    public init(
        host: String = "127.0.0.1",
        port: Int = 8787,
        cors: Bool = false,
        allowedOrigins: [String] = ServerSecurityPolicy.defaultAllowedOrigins,
        originCheckEnabled: Bool = true,
        token: String? = nil,
        tokenWasAutoGenerated: Bool = false,
        publicHealth: Bool = false,
        maxBodyBytes: Int = 32 * 1024 * 1024
    ) {
        self.host = host
        self.port = port
        self.cors = cors
        self.allowedOrigins = allowedOrigins
        self.originCheckEnabled = originCheckEnabled
        self.token = token
        self.tokenWasAutoGenerated = tokenWasAutoGenerated
        self.publicHealth = publicHealth
        self.maxBodyBytes = maxBodyBytes
    }

    public var healthRequiresAuthentication: Bool {
        token != nil && !publicHealth && !ServerSecurityPolicy.isLoopbackHost(host)
    }
}
