import Foundation
import ArgumentParser

extension ConfigBuilder {

    // MARK: server flags

    static func applyServerFlags(_ cmd: BgBgOneCommand, into cfg: inout Config) throws {
        if let host = cmd.host { cfg.server.host = host }
        if let port = cmd.port {
            guard (1...65535).contains(port) else {
                throw flagInvalid("--port must be 1..65535, got: \(port)", origin: "--port", value: String(port))
            }
            cfg.server.port = port
        }
        if cmd.cors { cfg.server.cors = true }
        if let origins = cmd.allowedOrigins {
            cfg.server.allowedOrigins = ServerSecurityPolicy.defaultAllowedOrigins + parseCommaList(origins)
        }
        if cmd.noOriginCheck { cfg.server.originCheckEnabled = false }
        if let token = cmd.token {
            guard !token.isEmpty else {
                throw flagInvalid("--token cannot be empty", origin: "--token", value: nil)
            }
            cfg.server.token = token
            cfg.server.tokenWasAutoGenerated = false
        }
        if cmd.tokenAuto {
            cfg.server.token = UUID().uuidString.replacingOccurrences(of: "-", with: "")
            cfg.server.tokenWasAutoGenerated = true
        }
        if cmd.publicHealth { cfg.server.publicHealth = true }
        if let mb = cmd.maxBodyMb {
            guard (1...512).contains(mb) else {
                throw flagInvalid("--max-body-mb must be 1..512, got: \(mb)", origin: "--max-body-mb", value: String(mb))
            }
            cfg.server.maxBodyBytes = mb * 1024 * 1024
        }
        if cmd.footgun {
            cfg.server.originCheckEnabled = false
            cfg.server.cors = true
            cfg.server.allowedOrigins = ["*"]
        }
    }

    // MARK: processing flags

    /// Returns whether any image-processing flag was seen (used to gate --server combination).
    static func applyProcessingFlags(_ cmd: BgBgOneCommand, into cfg: inout Config) throws -> Bool {
        var saw = false
        if let o = cmd.output { cfg.output = o; saw = true }
        if let d = cmd.outDir { cfg.outputDir = d; saw = true }
        if let f = cmd.outputFormatRaw {
            guard let fmt = OutputFormat.parseCanonical(f) else {
                throw flagInvalid("unknown --format value: \(f) (allowed: \(CLIContract.outputFormats.joined(separator: ", ")))", origin: "--format", value: f)
            }
            cfg.outputFormat = fmt; saw = true
        }
        if let q = cmd.quality {
            guard (1...100).contains(q) else {
                throw flagInvalid("--quality must be 1..100, got: \(q)", origin: "--quality", value: String(q))
            }
            cfg.quality = q; saw = true
        }
        if let bg = cmd.bg { cfg.background = try parseBackground(bg); saw = true }
        if let v = cmd.bgFit {
            guard let f = BgFit(rawValue: v) else {
                throw flagInvalid("unknown --bg-fit value: \(v) (allowed: \(CLIContract.bgFits.joined(separator: ", ")))", origin: "--bg-fit", value: v)
            }
            cfg.bgFit = f; saw = true
        }
        if let ch = cmd.channels {
            let v = ParameterParser.normalize(ch)
            switch v {
            case "rgba": cfg.maskOnly = false
            case "alpha": cfg.maskOnly = true; cfg.outputFormat = .png
            default:
                throw flagInvalid("unknown --channels value: \(v) (allowed: rgba, alpha)", origin: "--channels", value: v)
            }
            saw = true
        }
        if let m = cmd.cropMargin {
            cfg.cropMargins = try mapParameterParserError("--crop-margin", code: ErrorCodes.parseCropMarginInvalid) { try ParameterParser.parseCropMargins(m) }; saw = true
        }
        if cmd.crop { cfg.cropToSubject = true; saw = true }
        if let r = cmd.roi { cfg.roi = try mapParameterParserError("--roi", code: ErrorCodes.parseRoiInvalid) { try ParameterParser.parseROI(r) }; saw = true }
        if let t = cmd.type {
            cfg.algo = try mapParameterParserError("--type", code: ErrorCodes.parseFlagValueInvalid) { try ParameterParser.parseForegroundType(t).algo }; saw = true
        }
        if cmd.multi { cfg.multiInstance = true; saw = true }
        if let n = cmd.instanceNaming { cfg.instanceNamingTemplate = n; saw = true }
        if let s = cmd.shadowType {
            switch ParameterParser.normalize(s) {
            case "none": cfg.dropShadow = false
            case "auto", "drop", "3d", "car": cfg.dropShadow = true
            default:
                throw flagInvalid("unknown --shadow-type value: \(s) (allowed: auto, drop, 3D, car, none)", origin: "--shadow-type", value: s)
            }
            saw = true
        }
        if let o = cmd.shadowOpacity {
            cfg.shadowOpacity = try mapParameterParserError("--shadow-opacity", code: ErrorCodes.parseFlagValueInvalid) { try ParameterParser.parseShadowOpacity(o) }; saw = true
        }
        if let st = cmd.semitransparency {
            cfg.semitransparency = try mapParameterParserError("--semitransparency", code: ErrorCodes.parseFlagValueInvalid) {
                try ParameterParser.parseBoolean(st, default: true, code: "invalid_semitransparency", title: "Invalid semitransparency parameter given")
            }
            saw = true
        }
        if cmd.json && cmd.ndjson {
            throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--json and --ndjson are mutually exclusive", hint: "use one of --json or --ndjson")
        }
        if cmd.json { cfg.outputMode = .json; saw = true }
        if cmd.ndjson { cfg.outputMode = .ndjson; saw = true }
        if cmd.quiet && cmd.verbose {
            throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--quiet and --verbose are mutually exclusive", hint: "use one of --quiet or --verbose")
        }
        if cmd.quiet { cfg.quiet = true }
        if cmd.verbose { cfg.verbose = true }
        for raw in cmd.filter {
            let chain = try FilterParser.parse(raw)
            try FilterRegistry.validate(chain)
            if !chain.isEmpty { cfg.filters.append(chain) }
            saw = true
        }
        return saw
    }

    // MARK: helpers

    static func parseCommaList(_ raw: String) -> [String] {
        raw.split(separator: ",").map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }
    }

    static func parseBackground(_ spec: String) throws -> Background {
        if spec.hasPrefix("color:") { return .solidColor(try ColourParser.parse(String(spec.dropFirst("color:".count)))) }
        if spec.hasPrefix("image:") { return .image(String(spec.dropFirst("image:".count))) }
        throw flagInvalid("--bg must be color:<spec> or image:<path>, got: \(spec)", origin: "--bg", value: spec)
    }

    static func flagInvalid(_ message: String, origin: String, value: String?) -> BgBgOneError {
        var ctx: [String: String] = [:]
        if let v = value { ctx["value"] = v }
        return BgBgOneError.parser(ErrorCodes.parseFlagValueInvalid, message, origin: origin, context: ctx)
    }

    static func validate(_ cfg: Config, isStdoutTTY: Bool) throws {
        let readsFromStdin = cfg.inputs.contains("-")
        if cfg.output != nil && cfg.outputDir != nil {
            throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "use either -o/--output or --out-dir, not both")
        }
        if cfg.output == "-" {
            if cfg.outputMode != .standard {
                throw BgBgOneError.userError(
                    ErrorCodes.userOutputPathInvalid,
                    "-o - cannot be combined with --json/--ndjson because image bytes and metadata would share stdout",
                    hint: "write image bytes to a file or omit --json/--ndjson"
                )
            }
            if isStdoutTTY {
                throw BgBgOneError.userError(
                    ErrorCodes.userStdoutTTYRefuse,
                    "refusing to write binary image data to a terminal. Redirect stdout or pass a real -o path.",
                    hint: "use -o out.png or redirect stdout"
                )
            }
        }
        if cfg.inputs.count > 1 && cfg.output != nil {
            throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "-o cannot be used with multiple inputs; use --out-dir", hint: "use --out-dir <dir>")
        }
        if let outDir = cfg.outputDir {
            try validateBatchOutputNames(inputs: cfg.inputs, outDir: outDir, format: cfg.outputFormat)
        }
        if cfg.multiInstance {
            if cfg.output != nil {
                throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "--multi can emit multiple files; use --out-dir or omit output to write next to the input")
            }
            if cfg.maskOnly {
                throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--multi and --channels alpha are mutually exclusive")
            }
            if readsFromStdin {
                throw BgBgOneError.userError(ErrorCodes.userInputCountMismatch, "--multi cannot read from stdin because instance filenames need a file input stem")
            }
        }
        if readsFromStdin && cfg.outputDir != nil {
            throw BgBgOneError.userError(ErrorCodes.userOutputPathInvalid, "stdin input has no output filename; use -o <file> instead of --out-dir", hint: "use -o <file>")
        }
    }

    static func validateBatchOutputNames(inputs: [String], outDir: String, format: OutputFormat) throws {
        var seen: [String: String] = [:]
        for input in inputs where input != "-" {
            guard let path = OutputNaming.batchOutputPath(inputPath: input, outDir: outDir, format: format) else { continue }
            if let first = seen[path] {
                throw BgBgOneError.userError(
                    ErrorCodes.userBatchOutputConflict,
                    "batch output filename collision: \(first) and \(input) both write \(path)",
                    origin: "--out-dir",
                    context: ["first": first, "second": input, "output": path],
                    hint: "rename one input or use separate output directories"
                )
            }
            seen[path] = input
        }
    }

    // MARK: parser-error translation

    static func translate(parserError: Error, args: [String]) -> BgBgOneError {
        let msg = BgBgOneCommand.message(for: parserError)
        let lower = msg.lowercased()
        if lower.contains("unknown") || lower.contains("unexpected") {
            return BgBgOneError.parser(ErrorCodes.parseFlagUnknown, msg, hint: "run `bgbgone --help` for the supported flags")
        }
        if lower.contains("missing value") || lower.contains("requires a value") {
            return BgBgOneError.parser(ErrorCodes.parseFlagMissingValue, msg)
        }
        return BgBgOneError.parser(ErrorCodes.parseFlagValueInvalid, msg)
    }
}
