import Foundation
import ArgumentParser

extension ConfigBuilder {

    // MARK: server flags

    static func applyServerFlags(_ cmd: BgBgOneCommand, into cfg: inout Config) throws {
        if let host = cmd.host { cfg.server.host = host }
        if let port = cmd.port {
            guard (1...65535).contains(port) else {
                throw flagInvalid("--port must be 1..65535, got: \(port)", origin: "--port", value: String(port))
            }
            cfg.server.port = port
        }
        if cmd.cors { cfg.server.cors = true }
        if let origins = cmd.allowedOrigins {
            cfg.server.allowedOrigins = ServerSecurityPolicy.defaultAllowedOrigins + parseCommaList(origins)
        }
        if cmd.noOriginCheck { cfg.server.originCheckEnabled = false }
        if let token = cmd.token {
            guard !token.isEmpty else {
                throw flagInvalid("--token cannot be empty", origin: "--token", value: nil)
            }
            cfg.server.token = token
            cfg.server.tokenWasAutoGenerated = false
        }
        if cmd.tokenAuto {
            cfg.server.token = UUID().uuidString.replacingOccurrences(of: "-", with: "")
            cfg.server.tokenWasAutoGenerated = true
        }
        if cmd.publicHealth { cfg.server.publicHealth = true }
        if let mb = cmd.maxBodyMb {
            guard (1...512).contains(mb) else {
                throw flagInvalid("--max-body-mb must be 1..512, got: \(mb)", origin: "--max-body-mb", value: String(mb))
            }
            cfg.server.maxBodyBytes = mb * 1024 * 1024
        }
        if cmd.footgun {
            cfg.server.originCheckEnabled = false
            cfg.server.cors = true
            cfg.server.allowedOrigins = ["*"]
        }
    }

    // MARK: processing flags

    /// Returns whether any image-processing flag was seen (used to gate --server combination).
    static func applyProcessingFlags(_ cmd: BgBgOneCommand, into cfg: inout Config) throws -> Bool {
        var saw = false
        if let o = cmd.output { cfg.output = o; saw = true }
        if let d = cmd.outDir { cfg.outputDir = d; saw = true }
        if let f = cmd.outputFormatRaw {
            guard let fmt = OutputFormat.parse(f) else {
                throw flagInvalid("unknown --to value: \(f) (allowed: png, jpg/jpeg, zip, heic, avif, tiff)", origin: "--to", value: f)
            }
            cfg.outputFormat = fmt; saw = true
        }
        if let q = cmd.quality {
            guard (1...100).contains(q) else {
                throw flagInvalid("--quality must be 1..100, got: \(q)", origin: "--quality", value: String(q))
            }
            cfg.quality = q; saw = true
        }
        if let bg = cmd.bg { cfg.background = try parseBackground(bg); saw = true }
        if let c = cmd.bgColor {
            cfg.background = .solidColor(try ColourParser.parse(ServerCompatibilityParser.normalizedColor(c)))
            saw = true
        }
        if let p = cmd.bgImage { cfg.background = .image(p); saw = true }
        if let v = cmd.bgFit {
            guard let f = BgFit(rawValue: v) else {
                throw flagInvalid("unknown --bg-fit value: \(v) (allowed: cover, contain, tile, center)", origin: "--bg-fit", value: v)
            }
            cfg.bgFit = f; saw = true
        }
        if cmd.maskOnly { cfg.maskOnly = true; saw = true }
        if let ch = cmd.channels {
            let v = ServerCompatibilityParser.normalize(ch)
            switch v {
            case "rgba": cfg.maskOnly = false
            case "alpha": cfg.maskOnly = true; cfg.outputFormat = .png
            default:
                throw flagInvalid("unknown --channels value: \(v) (allowed: rgba, alpha)", origin: "--channels", value: v)
            }
            saw = true
        }
        if let f = cmd.feather {
            guard f >= 0 else { throw flagInvalid("--feather must be non-negative, got: \(f)", origin: "--feather", value: String(f)) }
            cfg.feather = f; saw = true
        }
        if let t = cmd.threshold {
            guard (0...1).contains(t) else { throw flagInvalid("--threshold must be 0..1, got: \(t)", origin: "--threshold", value: String(t)) }
            cfg.threshold = t; saw = true
        }
        if let p = cmd.padding {
            let parsed = try parsePadding(p)
            cfg.padding = parsed.value; cfg.paddingIsPercent = parsed.isPercent; saw = true
        }
        if let m = cmd.cropMargin {
            cfg.cropMargins = try mapAPIParserError { try ServerCompatibilityParser.parseCropMargins(m) }; saw = true
        }
        if cmd.crop { cfg.cropToSubject = true; saw = true }
        if let r = cmd.roi { cfg.roi = try mapAPIParserError { try ServerCompatibilityParser.parseROI(r) }; saw = true }
        if let s = cmd.scale { cfg.scalePercent = try mapAPIParserError { try ServerCompatibilityParser.parseScale(s) }; saw = true }
        if let p = cmd.position {
            cfg.position = try mapAPIParserError { try ServerCompatibilityParser.parsePosition(p, scalePercent: cfg.scalePercent) }
            saw = true
        }
        if let v = cmd.algo {
            guard let a = Algo(rawValue: v) else {
                throw flagInvalid("unknown --algo value: \(v) (allowed: auto, vn-mask, person, saliency)", origin: "--algo", value: v)
            }
            cfg.algo = a; saw = true
        }
        if let t = cmd.type {
            cfg.algo = try mapAPIParserError { try ServerCompatibilityParser.parseForegroundType(t).algo }; saw = true
        }
        if cmd.multi { cfg.multiInstance = true; saw = true }
        if let n = cmd.instanceNaming { cfg.instanceNamingTemplate = n; saw = true }
        if cmd.shadow { cfg.dropShadow = true; saw = true }
        if let s = cmd.shadowType {
            switch ServerCompatibilityParser.normalize(s) {
            case "none": cfg.dropShadow = false
            case "auto", "drop", "3d", "car": cfg.dropShadow = true
            default:
                throw flagInvalid("unknown --shadow-type value: \(s) (allowed: auto, drop, 3D, car, none)", origin: "--shadow-type", value: s)
            }
            saw = true
        }
        if let o = cmd.shadowOpacity {
            cfg.shadowOpacity = try mapAPIParserError { try ServerCompatibilityParser.parseShadowOpacity(o) }; saw = true
        }
        if let st = cmd.semitransparency {
            cfg.semitransparency = try mapAPIParserError {
                try ServerCompatibilityParser.parseBoolean(st, default: true, code: "invalid_semitransparency", title: "Invalid semitransparency parameter given")
            }
            saw = true
        }
        if cmd.json && cmd.ndjson {
            throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--json and --ndjson are mutually exclusive", hint: "use one of --json or --ndjson")
        }
        if cmd.json { cfg.outputMode = .json; saw = true }
        if cmd.ndjson { cfg.outputMode = .ndjson; saw = true }
        if cmd.quiet && cmd.verbose {
            throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--quiet and --verbose are mutually exclusive", hint: "use one of --quiet or --verbose")
        }
        if cmd.quiet { cfg.quiet = true }
        if cmd.verbose { cfg.verbose = true }
        for raw in cmd.filter {
            let chain = try FilterParser.parse(raw)
            if !chain.isEmpty { cfg.filters.append(chain) }
            saw = true
        }
        return saw
    }

    // MARK: helpers

    static func parseCommaList(_ raw: String) -> [String] {
        raw.split(separator: ",").map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }
    }

    static func parseBackground(_ spec: String) throws -> Background {
        if spec.hasPrefix("color:") { return .solidColor(try ColourParser.parse(String(spec.dropFirst("color:".count)))) }
        if spec.hasPrefix("image:") { return .image(String(spec.dropFirst("image:".count))) }
        throw flagInvalid("--bg must be color:<spec> or image:<path>, got: \(spec)", origin: "--bg", value: spec)
    }

    static func parsePadding(_ raw: String) throws -> (value: Double, isPercent: Bool) {
        if raw.hasSuffix("%") {
            let body = String(raw.dropLast())
            guard let n = Double(body), n >= 0 else {
                throw flagInvalid("invalid --padding percent: \(raw)", origin: "--padding", value: raw)
            }
            return (n / 100.0, true)
        }
        guard let n = Double(raw), n >= 0 else {
            throw flagInvalid("invalid --padding: \(raw)", origin: "--padding", value: raw)
        }
        return (n, false)
    }

    static func flagInvalid(_ message: String, origin: String, value: String?) -> BgBgOneError {
        var ctx: [String: String] = [:]
        if let v = value { ctx["value"] = v }
        return BgBgOneError.parser(ErrorCodes.parseFlagValueInvalid, message, origin: origin, context: ctx)
    }

    static func validate(_ cfg: Config) throws {
        let readsFromStdin = cfg.inputs.contains("-")
        if cfg.output != nil && cfg.outputDir != nil {
            throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "use either -o/--output or --out-dir, not both")
        }
        if cfg.inputs.count > 1 && cfg.output != nil {
            throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "-o cannot be used with multiple inputs; use --out-dir", hint: "use --out-dir <dir>")
        }
        if cfg.multiInstance {
            if cfg.output != nil {
                throw BgBgOneError.userError(ErrorCodes.userBatchOutputConflict, "--multi can emit multiple files; use --out-dir or omit output to write next to the input")
            }
            if cfg.maskOnly {
                throw BgBgOneError.userError(ErrorCodes.parseFlagDuplicate, "--multi and --mask-only are mutually exclusive")
            }
            if readsFromStdin {
                throw BgBgOneError.userError(ErrorCodes.userInputCountMismatch, "--multi cannot read from stdin because instance filenames need a file input stem")
            }
        }
        if readsFromStdin && cfg.outputDir != nil {
            throw BgBgOneError.userError(ErrorCodes.userOutputPathInvalid, "stdin input has no output filename; use -o <file> instead of --out-dir", hint: "use -o <file>")
        }
    }

    // MARK: parser-error translation

    static func translate(parserError: Error, args: [String]) -> BgBgOneError {
        let msg = BgBgOneCommand.message(for: parserError)
        let lower = msg.lowercased()
        if lower.contains("unknown") || lower.contains("unexpected") {
            return BgBgOneError.parser(ErrorCodes.parseFlagUnknown, msg, hint: "run `bgbgone --help` for the supported flags")
        }
        if lower.contains("missing value") || lower.contains("requires a value") {
            return BgBgOneError.parser(ErrorCodes.parseFlagMissingValue, msg)
        }
        return BgBgOneError.parser(ErrorCodes.parseFlagValueInvalid, msg)
    }
}
