// Auto-generated by make — do not edit
let buildVersion = "1.0.0"
let buildCommit = "612826e"
let buildBranch = "main"
let buildDate = "2026-05-23 23:24:53 UTC"
let buildSwiftVersion = "6.3.1"
let buildOS = "macOS 26.1"
