// Auto-generated by make — do not edit
let buildVersion = "0.1.36"
let buildCommit = "03dee5c"
let buildBranch = "main"
let buildDate = "2026-05-22 09:30:24 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
