// Auto-generated by make — do not edit
let buildVersion = "0.1.37"
let buildCommit = "50ae467"
let buildBranch = "main"
let buildDate = "2026-05-22 11:34:33 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
