import Foundation
import Darwin
import BgBgOneCore

struct BgBgOneHTTPServer {
    let config: ServerConfig
    let quiet: Bool

    func start() throws -> Never {
        let socketFD = try makeListeningSocket(host: config.host, port: config.port)
        if !quiet {
            printStderr("bgbgone server v\(buildVersion)")
            printStderr("endpoint: http://\(config.host):\(config.port)")
            printStderr("origin: \(config.originCheckEnabled ? "localhost only" : "disabled")")
            printStderr("cors: \(config.cors ? "enabled" : "disabled")")
            printStderr("token: \(config.token == nil ? "none" : "required")")
            if config.tokenWasAutoGenerated, let token = config.token {
                printStderr("token value: \(token)")
            }
            printStderr("ready")
        }

        DispatchQueue.global(qos: .userInitiated).async {
            while true {
                let clientFD = accept(socketFD, nil, nil)
                if clientFD < 0 {
                    continue
                }
                DispatchQueue.global(qos: .userInitiated).async {
                    ServerConnection(fileDescriptor: clientFD, config: config).start()
                }
            }
        }
        dispatchMain()
    }

    private func makeListeningSocket(host: String, port: Int) throws -> Int32 {
        let fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else {
            throw BgBgOneError.frameworkError("cannot create server socket")
        }

        var yes: Int32 = 1
        setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &yes, socklen_t(MemoryLayout<Int32>.size))

        var address = sockaddr_in()
        address.sin_family = sa_family_t(AF_INET)
        address.sin_port = UInt16(port).bigEndian
        address.sin_addr = in_addr(s_addr: ipv4Address(host))

        let bindResult = withUnsafePointer(to: &address) { pointer in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                bind(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard bindResult == 0 else {
            close(fd)
            throw BgBgOneError.frameworkError("cannot bind server to \(host):\(port)")
        }
        guard listen(fd, SOMAXCONN) == 0 else {
            close(fd)
            throw BgBgOneError.frameworkError("cannot listen on \(host):\(port)")
        }
        return fd
    }

    private func ipv4Address(_ host: String) -> in_addr_t {
        switch host.lowercased() {
        case "0.0.0.0":
            return INADDR_ANY.bigEndian
        case "localhost", "127.0.0.1":
            return INADDR_LOOPBACK.bigEndian
        default:
            var addr = in_addr()
            if inet_pton(AF_INET, host, &addr) == 1 {
                return addr.s_addr
            }
            return INADDR_LOOPBACK.bigEndian
        }
    }
}

private final class ServerConnection: @unchecked Sendable {
    private let fileDescriptor: Int32
    private let config: ServerConfig

    init(fileDescriptor: Int32, config: ServerConfig) {
        self.fileDescriptor = fileDescriptor
        self.config = config
    }

    func start() {
        let requestResult = readRequest()
        Task {
            let response: HTTPResponse
            switch requestResult {
            case .success(let request):
                response = await self.handle(request)
            case .failure(let error):
                response = .json(status: error.status, body: errorJSON(error.message, type: error.type))
            }
            self.send(response)
        }
    }

    private func readRequest() -> Result<HTTPRequest, RequestReadError> {
        var buffer = Data()
        var chunk = [UInt8](repeating: 0, count: 64 * 1024)
        while true {
            let n = recv(fileDescriptor, &chunk, chunk.count, 0)
            if n <= 0 {
                return .failure(RequestReadError(status: 400, message: "cannot read request", type: "invalid_request_error"))
            }
            buffer.append(chunk, count: n)
            if buffer.count > config.maxBodyBytes + 64 * 1024 {
                return .failure(RequestReadError(status: 413, message: "request body is too large", type: "request_too_large"))
            }
            if let request = HTTPRequest.parse(buffer) {
                if request.body.count > config.maxBodyBytes {
                    return .failure(RequestReadError(status: 413, message: "request body is too large", type: "request_too_large"))
                }
                return .success(request)
            }
        }
    }

    private func handle(_ request: HTTPRequest) async -> HTTPResponse {
        if request.method == "OPTIONS" {
            return preflight(origin: request.header("origin"), requestedHeaders: request.header("access-control-request-headers"))
        }

        let origin = request.header("origin")
        if config.originCheckEnabled && !ServerSecurityPolicy.isAllowedOrigin(origin, allowedOrigins: config.allowedOrigins) {
            return json(status: 403, body: errorJSON("Origin '\(origin ?? "unknown")' is not allowed.", type: "forbidden"), origin: origin)
        }

        if shouldCheckToken(for: request.path),
           !ServerSecurityPolicy.isValidToken(
                authorization: request.header("authorization"),
                apiKey: request.header("x-api-key"),
                expected: config.token
           ) {
            return json(
                status: 401,
                body: apiErrorJSON(code: "authentication_error", title: "Invalid or missing token."),
                origin: origin,
                extraHeaders: ["WWW-Authenticate": "Bearer"]
            )
        }

        switch (request.method, request.path) {
        case ("GET", "/health"):
            return json(status: 200, body: healthJSON(), origin: origin)
        case ("GET", "/v1.0/account"), ("GET", "/account"):
            return json(status: 200, body: accountJSON(), origin: origin)
        case ("POST", "/v1.0/bgbgone"), ("POST", "/bgbgone"):
            return await handleRemoveBackground(request, origin: origin)
        case ("POST", "/v1.0/improve"), ("POST", "/improve"):
            let error = ServerAPIError.notImplementable("image improvement submissions require a remote training program")
            return json(status: error.status, body: error.json(), origin: origin)
        default:
            return json(status: 404, body: apiErrorJSON(code: "not_found", title: "not found"), origin: origin)
        }
    }

    private func handleRemoveBackground(_ request: HTTPRequest, origin: String?) async -> HTTPResponse {
        do {
            let form = try parseForm(request)
            let tempDir = try FileManager.default.url(
                for: .itemReplacementDirectory,
                in: .userDomainMask,
                appropriateFor: URL(fileURLWithPath: NSTemporaryDirectory()),
                create: true
            )
            defer { try? FileManager.default.removeItem(at: tempDir) }

            let inputPath = try writeInputFile(form: form, tempDir: tempDir)
            let bgPath = try writeBackgroundFileIfPresent(form: form, tempDir: tempDir)
            var removal = try ServerRemovalRequest.parse(
                form: form,
                inputPath: inputPath.path,
                backgroundImagePath: bgPath?.path,
                acceptHeader: request.header("accept")
            )
            let outURL = tempDir.appendingPathComponent("result.\(removal.config.outputFormat.extensionForFile)")
            removal.config.output = outURL.path

            let result = try await MainActor.run {
                try BgBgOne.run(removal.config)
            }
            let imageData = try Data(contentsOf: URL(fileURLWithPath: result.output))
            let metadata = metadataHeaders(result: result, typeHeaderValue: removal.typeHeaderValue)

            switch removal.responseKind {
            case .image:
                return binary(status: 200, body: imageData, contentType: contentType(for: removal.config.outputFormat), origin: origin, extraHeaders: metadata)
            case .json:
                let body = """
                {"data":{"result_b64":"\(imageData.base64EncodedString())","foreground_top":0,"foreground_left":0,"foreground_width":\(result.width),"foreground_height":\(result.height)}}
                """
                return json(status: 200, body: body, origin: origin, extraHeaders: metadata)
            case .zip:
                return binary(status: 200, body: imageData, contentType: "application/zip", origin: origin, extraHeaders: metadata)
            }
        } catch let error as ServerAPIError {
            return json(status: error.status, body: error.json(), origin: origin)
        } catch let error as BgBgOneError {
            return json(status: statusCode(for: error), body: apiErrorJSON(code: errorType(for: error), title: error.message), origin: origin)
        } catch {
            return json(status: 500, body: apiErrorJSON(code: "server_error", title: error.localizedDescription), origin: origin)
        }
    }

    private func parseForm(_ request: HTTPRequest) throws -> ServerForm {
        let contentType = request.header("content-type") ?? ""
        if contentType.lowercased().contains("multipart/form-data") {
            guard let boundary = multipartBoundary(from: contentType) else {
                throw BgBgOneError.parser("multipart boundary is required")
            }
            return try ServerFormParser.parseMultipart(request.body, boundary: boundary)
        }
        if contentType.lowercased().contains("application/json") {
            return try ServerFormParser.parseJSON(request.body)
        }
        if contentType.lowercased().contains("application/x-www-form-urlencoded") || contentType.isEmpty {
            return ServerFormParser.parseURLEncoded(request.body)
        }
        throw BgBgOneError.parser("unsupported content type: \(contentType)")
    }

    private func writeInputFile(form: ServerForm, tempDir: URL) throws -> URL {
        if let file = form.files["image_file"] {
            return try writeFile(data: file.data, filename: file.filename, tempDir: tempDir, fallbackName: "input")
        }
        if form.fields["image_url"] != nil {
            return tempDir.appendingPathComponent("remote-url-placeholder.img")
        }
        if let encoded = form.fields["image_file_b64"], let data = Data(base64Encoded: encoded) {
            return try writeFile(data: data, filename: "input", tempDir: tempDir, fallbackName: "input")
        }
        return tempDir.appendingPathComponent("missing-input-placeholder.img")
    }

    private func writeBackgroundFileIfPresent(form: ServerForm, tempDir: URL) throws -> URL? {
        if let file = form.files["bg_image_file"] {
            return try writeFile(data: file.data, filename: file.filename, tempDir: tempDir, fallbackName: "background")
        }
        if form.fields["bg_image_url"] != nil {
            return nil
        }
        if let encoded = form.fields["bg_image_file_b64"], let data = Data(base64Encoded: encoded) {
            return try writeFile(data: data, filename: "background", tempDir: tempDir, fallbackName: "background")
        }
        return nil
    }

    private func writeFile(data: Data, filename: String, tempDir: URL, fallbackName: String) throws -> URL {
        guard !data.isEmpty else {
            throw BgBgOneError.userError("\(fallbackName) image data is empty")
        }
        let ext = (filename as NSString).pathExtension
        let safeExt = ext.isEmpty ? "img" : ext
        let url = tempDir.appendingPathComponent("\(fallbackName).\(safeExt)")
        try data.write(to: url, options: .atomic)
        return url
    }

    private func shouldCheckToken(for path: String) -> Bool {
        guard config.token != nil else { return false }
        if path == "/health" && !config.healthRequiresAuthentication {
            return false
        }
        return true
    }

    private func preflight(origin: String?, requestedHeaders: String?) -> HTTPResponse {
        var headers: [String: String] = ["Content-Length": "0"]
        if config.cors {
            applyCORSHeaders(&headers, origin: origin)
            headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
            headers["Access-Control-Allow-Headers"] = requestedHeaders ?? "Content-Type, Authorization"
            headers["Access-Control-Max-Age"] = "86400"
        }
        return HTTPResponse(status: 204, headers: headers, body: Data())
    }

    private func json(status: Int, body: String, origin: String?, extraHeaders: [String: String] = [:]) -> HTTPResponse {
        var headers = ["Content-Type": "application/json; charset=utf-8"]
        for (key, value) in extraHeaders {
            headers[key] = value
        }
        applyCORSHeaders(&headers, origin: origin)
        return HTTPResponse(status: status, headers: headers, body: Data(body.utf8))
    }

    private func binary(status: Int, body: Data, contentType: String, origin: String?, extraHeaders: [String: String] = [:]) -> HTTPResponse {
        var headers = ["Content-Type": contentType]
        for (key, value) in extraHeaders {
            headers[key] = value
        }
        applyCORSHeaders(&headers, origin: origin)
        return HTTPResponse(status: status, headers: headers, body: body)
    }

    private func applyCORSHeaders(_ headers: inout [String: String], origin: String?) {
        guard config.cors else { return }
        if !config.originCheckEnabled || config.allowedOrigins.contains("*") {
            headers["Access-Control-Allow-Origin"] = "*"
            return
        }
        if let origin, ServerSecurityPolicy.isAllowedOrigin(origin, allowedOrigins: config.allowedOrigins) {
            headers["Access-Control-Allow-Origin"] = origin
            headers["Vary"] = "Origin"
        }
    }

    private func send(_ response: HTTPResponse) {
        let data = response.serialize()
        data.withUnsafeBytes { raw in
            guard var base = raw.baseAddress else { return }
            var remaining = raw.count
            while remaining > 0 {
                let sent = Darwin.send(fileDescriptor, base, remaining, 0)
                if sent <= 0 { break }
                remaining -= sent
                base += sent
            }
        }
        close(fileDescriptor)
    }
}

private struct RequestReadError: Error {
    let status: Int
    let message: String
    let type: String
}

private struct HTTPRequest {
    let method: String
    let path: String
    let headers: [String: String]
    let body: Data

    func header(_ name: String) -> String? {
        headers[name.lowercased()]
    }

    static func parse(_ data: Data) -> HTTPRequest? {
        let separator = Data("\r\n\r\n".utf8)
        guard let headerRange = data.range(of: separator) else {
            return nil
        }
        let headerData = data[..<headerRange.lowerBound]
        guard let headerText = String(data: headerData, encoding: .utf8) else {
            return nil
        }
        let lines = headerText.components(separatedBy: "\r\n")
        guard let requestLine = lines.first else {
            return nil
        }
        let requestParts = requestLine.split(separator: " ", maxSplits: 2)
        guard requestParts.count >= 2 else {
            return nil
        }

        var headers: [String: String] = [:]
        for line in lines.dropFirst() {
            let parts = line.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
            guard parts.count == 2 else { continue }
            headers[String(parts[0]).lowercased()] = String(parts[1]).trimmingCharacters(in: .whitespaces)
        }

        let contentLength = Int(headers["content-length"] ?? "0") ?? 0
        let bodyStart = headerRange.upperBound
        guard data.count >= bodyStart + contentLength else {
            return nil
        }
        let fullPath = String(requestParts[1])
        let path = fullPath.split(separator: "?", maxSplits: 1).first.map(String.init) ?? fullPath
        return HTTPRequest(
            method: String(requestParts[0]).uppercased(),
            path: path,
            headers: headers,
            body: Data(data[bodyStart..<(bodyStart + contentLength)])
        )
    }
}

private struct HTTPResponse {
    let status: Int
    var headers: [String: String]
    let body: Data

    func serialize() -> Data {
        var responseHeaders = headers
        responseHeaders["Content-Length"] = "\(body.count)"
        responseHeaders["Connection"] = "close"
        let reason = reasonPhrase(for: status)
        var head = "HTTP/1.1 \(status) \(reason)\r\n"
        for (key, value) in responseHeaders.sorted(by: { $0.key < $1.key }) {
            head += "\(key): \(value)\r\n"
        }
        head += "\r\n"
        var out = Data(head.utf8)
        out.append(body)
        return out
    }

    static func json(status: Int, body: String) -> HTTPResponse {
        HTTPResponse(
            status: status,
            headers: ["Content-Type": "application/json; charset=utf-8"],
            body: Data(body.utf8)
        )
    }
}

private func multipartBoundary(from contentType: String) -> String? {
    for component in contentType.split(separator: ";") {
        let parts = component.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
        guard parts.count == 2 else { continue }
        if parts[0].trimmingCharacters(in: .whitespaces).lowercased() == "boundary" {
            return String(parts[1]).trimmingCharacters(in: .whitespaces).trimmingCharacters(in: CharacterSet(charactersIn: "\""))
        }
    }
    return nil
}

private func statusCode(for error: BgBgOneError) -> Int {
    switch error {
    case .parser, .userError:
        return 400
    case .noResult:
        return 422
    case .frameworkError:
        return 500
    }
}

private func errorType(for error: BgBgOneError) -> String {
    switch error {
    case .parser, .userError:
        return "invalid_request_error"
    case .noResult:
        return "no_result"
    case .frameworkError:
        return "server_error"
    }
}

private func errorJSON(_ message: String, type: String) -> String {
    """
    {"error":{"message":"\(JSONEscaper.escape(message))","type":"\(type)"}}
    """
}

private func apiErrorJSON(code: String, title: String, detail: String? = nil) -> String {
    ServerAPIError(status: 400, code: code, title: title, detail: detail).json()
}

private func healthJSON() -> String {
    """
    {"status":"ok","version":"\(buildVersion)","api":"bgbgone","local":true}
    """
}

private func accountJSON() -> String {
    """
    {"data":{"attributes":{"credits":{"total":0,"subscription":0,"payg":0,"enterprise":0},"api":{"free_calls":0,"sizes":"all"}}}}
    """
}

private func contentType(for format: OutputFormat) -> String {
    switch format {
    case .png: return "image/png"
    case .jpeg: return "image/jpeg"
    case .zip: return "application/zip"
    case .heic: return "image/heic"
    case .avif: return "image/avif"
    case .tiff: return "image/tiff"
    }
}

private func reasonPhrase(for status: Int) -> String {
    switch status {
    case 200: return "OK"
    case 204: return "No Content"
    case 400: return "Bad Request"
    case 401: return "Unauthorized"
    case 403: return "Forbidden"
    case 404: return "Not Found"
    case 413: return "Payload Too Large"
    case 422: return "Unprocessable Entity"
    case 501: return "Not Implemented"
    case 500: return "Internal Server Error"
    default: return "HTTP"
    }
}

private func metadataHeaders(result: RunResult, typeHeaderValue: String?) -> [String: String] {
    var headers = [
        "X-Width": "\(result.width)",
        "X-Height": "\(result.height)",
        "X-Credits-Charged": "0",
        "X-Foreground-Top": "0",
        "X-Foreground-Left": "0",
        "X-Foreground-Width": "\(result.width)",
        "X-Foreground-Height": "\(result.height)",
    ]
    if let typeHeaderValue {
        headers["X-Type"] = typeHeaderValue
    }
    return headers
}

private func printStderr(_ message: String) {
    FileHandle.standardError.write(Data((message + "\n").utf8))
}
