import Foundation
import BgBgOneCore

func runServerConfigTests() {
    test("--server enters server mode with secure localhost defaults") {
        let cfg = try ConfigParser.parse(args: ["--server"], isStdinTTY: true, isStdoutTTY: true)
        try assertEqual(cfg.mode, .serverRequested)
        try assertEqual(cfg.server.host, "127.0.0.1")
        try assertEqual(cfg.server.port, 8787)
        try assertFalse(cfg.server.cors)
        try assertTrue(cfg.server.originCheckEnabled)
        try assertEqual(cfg.server.allowedOrigins, ServerSecurityPolicy.defaultAllowedOrigins)
        try assertNil(cfg.server.token)
        try assertEqual(cfg.server.maxBodyBytes, 32 * 1024 * 1024)
    }

    test("--server parses host, port, CORS, token, public health, and body limit") {
        let cfg = try ConfigParser.parse(
            args: [
                "--server",
                "--host", "0.0.0.0",
                "--port", "19191",
                "--cors",
                "--allowed-origins", "http://localhost:3000,http://127.0.0.1:5173",
                "--token", "secret",
                "--public-health",
                "--max-body-mb", "64"
            ],
            isStdinTTY: true,
            isStdoutTTY: true
        )
        try assertEqual(cfg.server.host, "0.0.0.0")
        try assertEqual(cfg.server.port, 19191)
        try assertTrue(cfg.server.cors)
        try assertEqual(cfg.server.allowedOrigins, ServerSecurityPolicy.defaultAllowedOrigins + ["http://localhost:3000", "http://127.0.0.1:5173"])
        try assertEqual(cfg.server.token, "secret")
        try assertFalse(cfg.server.tokenWasAutoGenerated)
        try assertTrue(cfg.server.publicHealth)
        try assertEqual(cfg.server.maxBodyBytes, 64 * 1024 * 1024)
    }

    test("BGBGONE_TOKEN provides server token unless --token overrides it") {
        let envCfg = try ConfigParser.parse(
            args: ["--server"],
            isStdinTTY: true,
            isStdoutTTY: true,
            environment: ["BGBGONE_TOKEN": "env-secret"]
        )
        try assertEqual(envCfg.server.token, "env-secret")

        let cliCfg = try ConfigParser.parse(
            args: ["--server", "--token", "cli-secret"],
            isStdinTTY: true,
            isStdoutTTY: true,
            environment: ["BGBGONE_TOKEN": "env-secret"]
        )
        try assertEqual(cliCfg.server.token, "cli-secret")
    }

    test("--token-auto creates a token without echoing a fixed value in tests") {
        let cfg = try ConfigParser.parse(args: ["--server", "--token-auto"], isStdinTTY: true, isStdoutTTY: true)
        try assertTrue(cfg.server.tokenWasAutoGenerated)
        try assertNotNil(cfg.server.token)
        try assertTrue((cfg.server.token ?? "").count >= 32)
    }

    test("server-only flags require --server") {
        do {
            _ = try ConfigParser.parse(args: ["--port", "19191"], isStdinTTY: true, isStdoutTTY: true)
            throw TestFailure("expected throw")
        } catch let e as BgBgOneError {
            if case .userError(let message) = e {
                try assertTrue(message.contains("--server"))
            } else {
                throw TestFailure("wrong error: \(e)")
            }
        }
    }

    test("--server rejects positional image inputs") {
        do {
            _ = try ConfigParser.parse(args: ["--server", "in.jpg"], isStdinTTY: true, isStdoutTTY: true)
            throw TestFailure("expected throw")
        } catch let e as BgBgOneError {
            if case .userError(let message) = e {
                try assertTrue(message.contains("--server") && message.contains("input"))
            } else {
                throw TestFailure("wrong error: \(e)")
            }
        }
    }

    test("--server rejects image-processing flags") {
        for args in [["--server", "--to", "jpg"], ["--server", "--json"], ["--server", "-o", "out.png"]] {
            do {
                _ = try ConfigParser.parse(args: args, isStdinTTY: true, isStdoutTTY: true)
                throw TestFailure("expected throw for \(args)")
            } catch let e as BgBgOneError {
                if case .userError(let message) = e {
                    try assertTrue(message.contains("--server") && message.contains("options"))
                } else {
                    throw TestFailure("wrong error for \(args): \(e)")
                }
            }
        }
    }

    test("--port and --max-body-mb validate bounds") {
        for args in [["--server", "--port", "0"], ["--server", "--port", "70000"], ["--server", "--max-body-mb", "0"]] {
            do {
                _ = try ConfigParser.parse(args: args, isStdinTTY: true, isStdoutTTY: true)
                throw TestFailure("expected throw for \(args)")
            } catch let e as BgBgOneError {
                if case .parser = e { } else { throw TestFailure("wrong error for \(args): \(e)") }
            }
        }
    }

    test("--no-origin-check disables browser-origin filtering but keeps CORS off") {
        let cfg = try ConfigParser.parse(args: ["--server", "--no-origin-check"], isStdinTTY: true, isStdoutTTY: true)
        try assertFalse(cfg.server.originCheckEnabled)
        try assertFalse(cfg.server.cors)
        try assertEqual(cfg.server.allowedOrigins, ServerSecurityPolicy.defaultAllowedOrigins)
    }

    test("--footgun is shorthand for disabling origin checks and enabling wildcard CORS") {
        let cfg = try ConfigParser.parse(args: ["--server", "--footgun"], isStdinTTY: true, isStdoutTTY: true)
        try assertFalse(cfg.server.originCheckEnabled)
        try assertTrue(cfg.server.cors)
        try assertEqual(cfg.server.allowedOrigins, ["*"])
    }

    test("--allowed-origins is additive over the default localhost set") {
        let cfg = try ConfigParser.parse(args: ["--server", "--allowed-origins", "https://app.example.com"], isStdinTTY: true, isStdoutTTY: true)
        try assertEqual(cfg.server.allowedOrigins, ServerSecurityPolicy.defaultAllowedOrigins + ["https://app.example.com"])
    }

    test("--allowed-origins comma-separates and trims whitespace") {
        let cfg = try ConfigParser.parse(
            args: ["--server", "--allowed-origins", " http://localhost:3000 , http://127.0.0.1:5173 "],
            isStdinTTY: true,
            isStdoutTTY: true
        )
        try assertEqual(cfg.server.allowedOrigins, ServerSecurityPolicy.defaultAllowedOrigins + ["http://localhost:3000", "http://127.0.0.1:5173"])
    }

    test("--token cannot be empty") {
        do {
            _ = try ConfigParser.parse(args: ["--server", "--token", ""], isStdinTTY: true, isStdoutTTY: true)
            throw TestFailure("expected throw")
        } catch let e as BgBgOneError {
            if case .parser(let m) = e {
                try assertTrue(m.contains("--token"))
            } else {
                throw TestFailure("wrong error: \(e)")
            }
        }
    }

    test("BGBGONE_HOST and BGBGONE_PORT pre-seed the server bind") {
        let cfg = try ConfigParser.parse(
            args: ["--server"],
            isStdinTTY: true,
            isStdoutTTY: true,
            environment: ["BGBGONE_HOST": "0.0.0.0", "BGBGONE_PORT": "19292"]
        )
        try assertEqual(cfg.server.host, "0.0.0.0")
        try assertEqual(cfg.server.port, 19292)
    }

    test("BGBGONE_PORT outside the valid range is ignored, falling back to the default") {
        let cfg = try ConfigParser.parse(
            args: ["--server"],
            isStdinTTY: true,
            isStdoutTTY: true,
            environment: ["BGBGONE_PORT": "99999"]
        )
        try assertEqual(cfg.server.port, 8787)
    }

    test("--max-body-mb upper bound is honored (512 MiB max)") {
        do {
            _ = try ConfigParser.parse(args: ["--server", "--max-body-mb", "1024"], isStdinTTY: true, isStdoutTTY: true)
            throw TestFailure("expected throw")
        } catch let e as BgBgOneError {
            if case .parser = e { } else { throw TestFailure("wrong error: \(e)") }
        }
    }

    test("--public-health is parsed and stored when --server is given") {
        let cfg = try ConfigParser.parse(args: ["--server", "--public-health"], isStdinTTY: true, isStdoutTTY: true)
        try assertTrue(cfg.server.publicHealth)
    }
}
