#!/usr/bin/env bash
# extract-doc-blocks.sh -- walk every shipped .md and emit one TSV record
# per fenced ```bash / ```sh block:
#
#   file<TAB>start_line<TAB>end_line<TAB>image_path<TAB>kind<TAB>code_b64
#
# `kind` is one of: bgbgone | non_bgbgone | install | curl | other
# `image_path` is the ![alt](path) markdown image link found within 3
#   lines above or below the block (resolved relative to the .md file),
#   or "" if the block has no paired image.
# `code_b64` is base64 of the block body (newline-safe).
#
# This is the SSOT consumed by both:
#   - scripts/lint-doc-pairing.sh  (every block must have a paired image)
#   - scripts/test-doc-blocks.sh   (every bgbgone block must execute clean)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Files to scan: every shipped .md. Skip .build/, node_modules/, the plan
# directory under ~/.claude, the autogenerated docs/images/ folder, archive.
FILES=$(find "$ROOT" -type f -name '*.md' \
  ! -path '*/.build/*' ! -path '*/node_modules/*' \
  ! -path '*/docs/archive/*' \
  | sort)

classify() {
  local first="$1"
  case "$first" in
    bgbgone\ *|*\|*bgbgone*|cat\ *bgbgone*)  echo "bgbgone" ;;
    brew\ *|sudo\ brew*|sudo\ install*)      echo "install" ;;
    curl\ *)                                  echo "curl" ;;
    make\ *|git\ *|swift\ *|wrangler\ *)     echo "other" ;;
    *)                                        echo "non_bgbgone" ;;
  esac
}

# Find the first ![...](path) within ±3 lines of [start..end].
find_paired_image() {
  local file="$1" start="$2" end="$3"
  local lo=$((start - 4))
  local hi=$((end + 4))
  [ "$lo" -lt 1 ] && lo=1
  awk -v lo="$lo" -v hi="$hi" 'NR>=lo && NR<=hi {print}' "$file" \
    | grep -oE '!\[[^]]*\]\(([^)]+)\)' \
    | head -1 \
    | sed -E 's/!\[[^]]*\]\(([^)]+)\)/\1/'
}

for f in $FILES; do
  awk -v file="$f" '
    BEGIN { in_fence = 0; start = 0; lang = ""; body = "" }
    /^```bash$|^```sh$/ {
      if (!in_fence) { in_fence = 1; start = NR; lang = $0; body = ""; next }
    }
    /^```$/ {
      if (in_fence) {
        printf "FENCE\t%d\t%d\t%s\n", start, NR, body
        in_fence = 0; body = ""
        next
      }
    }
    { if (in_fence) { body = body $0 "\n" } }
  ' "$f" | while IFS=$'\t' read -r tag s e body; do
    [ "$tag" = "FENCE" ] || continue
    first_line=$(printf '%s' "$body" | head -1)
    kind=$(classify "$first_line")
    img=$(find_paired_image "$f" "$s" "$e" || true)
    code_b64=$(printf '%s' "$body" | base64)
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$f" "$s" "$e" "$img" "$kind" "$code_b64"
  done
done
